name: Chocolatine by OF_Jaggernaut

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MIRROR_URL: "git@github.com:FaroukJGRNT/Chocolatine-Test-Mirror.git"
  EXECUTABLES: "binary"

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    #needs: run_tests
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Mirroring
      uses: pixta-dev/repository-mirroring-action@v1
      with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
